### ISSUE TITLE
Issue after CSGO "Release Notes for 1/27/2021" Update

### ISSUE THREAD

**Issue by rpkaul** [Natanel-Shitrit/MiscChanger#8]
L 01/28/2021 - 01:38:58: [SM] Exception reported: Failed to get CCSPlayer::SetRank signature
L 01/28/2021 - 01:38:58: [SM] Blaming: MiscChanger.smx
L 01/28/2021 - 01:38:58: [SM] Call stack trace:
L 01/28/2021 - 01:38:58: [SM]   [0] SetFailState
L 01/28/2021 - 01:38:58: [SM]   [1] Line 932, C:\Users\Natanel\Desktop\Programming Stuff\SPEdit\MiscChanger\sourcemod\scripting\MiscChanger.sp::LoadGameData
L 01/28/2021 - 01:38:58: [SM]   [2] Line 178, C:\Users\Natanel\Desktop\Programming Stuff\SPEdit\MiscChanger\sourcemod\scripting\MiscChanger.sp::OnPluginStart
L 01/28/2021 - 01:38:58: [SM] Unable to load plugin "MiscChanger.smx": Error detected in plugin startup (see error logs)

**Comment by Natanel-Shitrit** [comment]
Working on a fix right now :)

**Comment by Natanel-Shitrit** [comment]
For Linux it should be fixed for now, please confirm so I can close it 😄.

**Comment by rpkaul** [comment]
Can Confirm its working fine 👍 
Thank you so much for quick response ,really appreciated. 💯

**Comment by Natanel-Shitrit** [comment]
PS: Windows is also fixed, I don't really know if someone is using this on windows, but I updated just in case.
